server:
  port: 5556
  error:
    include-stacktrace: never

spring:
  application:
    name: backend-app
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5433/backend-db
#    username: postgres
#    password: p1234
    data:
      - classpath:data.sql


logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO


security:
  jwt:
    token:
      secret-key: secret-key-56987454-jwt-security-token
      expiration: 1200600000